version: '3.7'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
      DATABASE_URI: "mysql+pymysql://root:pass5678@k8s-rds.cbf9oalhjjnm.eu-west-1.rds.amazonaws.com:3306/testdb"
      TEST_DATABASE_URI: "mysql+pymysql://root:pass1234@test-rds.cbf9oalhjjnm.eu-west-1.rds.amazonaws.com:3306/testdb"
      SECRET_KEY: "urhuthguhtvrtvtnefro"
    
  frontend:
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    container_name: frontend
