apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: pipeline
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-app
        image: aatkinson42/front-end:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app   
  namespace: pipeline
  labels:
    app: flask-app
spec:
  selector:
    app: flask   
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
