apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DATABASE_URI: "mysql+pymysql://root:pass5678@k8s-rds.cbf9oalhjjnm.eu-west-1.rds.amazonaws.com:3306/testdb"
  SECRET_KEY: "weyifhyrehfye"
  TEST_DATABASE_URI: "mysql+pymysql://root:pass1234@test-rds.cbf9oalhjjnm.eu-west-1.rds.amazonaws.com:3306/testdb"
